# Generated by Django 3.2.5 on 2021-07-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, unique=True)),
                ('students', models.ManyToManyField(related_name='grades', to='school_roster.Student')),
            ],
        ),
    ]
